// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"database/sql"
	"time"
)

type Author struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Bio       sql.NullString `json:"bio"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Quote struct {
	ID        int64          `json:"id"`
	Content   string         `json:"content"`
	AuthorID  int64          `json:"author_id"`
	Source    sql.NullString `json:"source"`
	Tags      []string       `json:"tags"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
