// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"context"
)

type Querier interface {
	CountAuthors(ctx context.Context) (int64, error)
	CountQuotes(ctx context.Context) (int64, error)
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error)
	CreateQuote(ctx context.Context, arg CreateQuoteParams) (Quote, error)
	DeleteAuthor(ctx context.Context, id int64) error
	DeleteQuote(ctx context.Context, id int64) error
	GetAuthor(ctx context.Context, id int64) (Author, error)
	GetQuote(ctx context.Context, id int64) (GetQuoteRow, error)
	GetRandomQuote(ctx context.Context) (GetRandomQuoteRow, error)
	ListAuthors(ctx context.Context, arg ListAuthorsParams) ([]Author, error)
	ListQuotes(ctx context.Context, arg ListQuotesParams) ([]ListQuotesRow, error)
	ListQuotesByAuthor(ctx context.Context, arg ListQuotesByAuthorParams) ([]ListQuotesByAuthorRow, error)
	SearchAuthorsByName(ctx context.Context, arg SearchAuthorsByNameParams) ([]Author, error)
	SearchQuotesByContent(ctx context.Context, arg SearchQuotesByContentParams) ([]SearchQuotesByContentRow, error)
	UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) (Author, error)
	UpdateQuote(ctx context.Context, arg UpdateQuoteParams) (Quote, error)
}

var _ Querier = (*Queries)(nil)
